# Generated by Django 5.2.16 on 2026-08-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='category',
            field=models.CharField(choices=[('table', 'Стол'), ('chair', 'Стул'), ('sofa', 'Диван')], db_index=True, default='table', max_length=10),
            preserve_default=False,
        ),
    ]
